FROM ruby:2.2.7

ENV APP_ROOT /usr/src/rails_base

WORKDIR $APP_ROOT

RUN apt-get update && \
    apt-get install -y nodejs \
                     npm \
                     mysql-client \
                     postgresql-client \
                     sqlite3 \
                     vim \
                     --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile $APP_ROOT
COPY Gemfile.lock $APP_ROOT

RUN \
  echo 'gem: --no-document' >> ~/.gemrc && \
  cp ~/.gemrc /etc/gemrc && \
  chmod uog+r /etc/gemrc && \
  bundle config --global build.nokogiri --use-system-libraries && \
  bundle config --global jobs 4 && \
  bundle install && \
  rm -rf ~/.gem

